


type Todo {
  id: ID!
  title: String!
  done: Boolean!
}

type Event {
  result : String
}

input TodoInput {

  title: String!

}

type Query {
  getTodos: [Todo]
}

type Mutation {
  addTodo(todo: TodoInput!): Event
  updateTodo(todo: TodoInput!): Event
  deleteTodo(todoId: String!): Event
}